# Site settings
title: Benjamin Beringue
description: Personal page
#baseurl: "" # the subpath of your site
url: "https://beringueb.github.io" # the base hostname & protocol for your site

# User settings
username: Benjamin Beringue
user_description: A soon to be cosmologist, finsihing its PhD at the University of Cambridge under the supervision of Dr Daan Meerburg.
user_title: Cosmologist
email: beringueb@gmail.com
# twitter_username: lorem_ipsum
github_username:  beringueb
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']


