# Site settings
title: Benjamin Beringue
description: Personal page
baseurl: "/index" # the subpath of your site, e.g. /blog
url: "https://beringueb.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Benjamin Beringue
user_description: A soon to be cosmologist, finsihing its PhD at the University of Cambridge under the supervision of Dr Daan Meerburg.
user_title: PhD student
email: bb510@cam.ac.uk
# twitter_username: lorem_ipsum
github_username:  beringueb
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
